"""esquema inicial: as 12 tabelas como estavam quando as migrações foram adotadas

Bancos criados antes disso (pelo create_all) são marcados como nesta versão por crosssell.db.init_db.

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 15:31:19.806731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('razao_receita', sa.String(), nullable=True),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=True),
    sa.Column('nome_normalizado', sa.String(), nullable=False),
    sa.Column('dominio', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('setor', sa.String(), nullable=True),
    sa.Column('cnae', sa.String(), nullable=True),
    sa.Column('natureza_juridica', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('investida', sa.Boolean(), nullable=True),
    sa.Column('porte', sa.String(), nullable=True),
    sa.Column('funcionarios', sa.Integer(), nullable=True),
    sa.Column('funcionarios_fonte', sa.String(), nullable=True),
    sa.Column('capital_social', sa.Double(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('pipedrive_org_id', sa.Integer(), nullable=True),
    sa.Column('enriquecido_em', sa.DateTime(), nullable=True),
    sa.Column('score_relacionamento', sa.Float(), nullable=False),
    sa.Column('score_componentes', sa.JSON(), nullable=False),
    sa.Column('noticias_em', sa.DateTime(), nullable=True),
    sa.Column('linkedin_em', sa.DateTime(), nullable=True),
    sa.Column('linkedin_pedido_em', sa.DateTime(), nullable=True),
    sa.Column('linkedin_site_em', sa.DateTime(), nullable=True),
    sa.Column('linkedin_busca_em', sa.DateTime(), nullable=True),
    sa.Column('linkedin_nao_encontrado', sa.Boolean(), nullable=False),
    sa.Column('linkedin_areas', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_cnpj'), ['cnpj'], unique=False)
        batch_op.create_index(batch_op.f('ix_empresas_dominio'), ['dominio'], unique=False)
        batch_op.create_index(batch_op.f('ix_empresas_nome_normalizado'), ['nome_normalizado'], unique=False)
        batch_op.create_index(batch_op.f('ix_empresas_pipedrive_org_id'), ['pipedrive_org_id'], unique=False)

    op.create_table('linkedin_pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('id_alvo', sa.String(), nullable=False),
    sa.Column('acao', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.Column('situacao', sa.String(), nullable=False),
    sa.Column('erro', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id')
    )
    with op.batch_alter_table('linkedin_pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_linkedin_pedidos_concluido_em'), ['concluido_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_linkedin_pedidos_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_linkedin_pedidos_id_alvo'), ['id_alvo'], unique=False)

    op.create_table('qualidade_ignoradas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(), nullable=False),
    sa.Column('em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fonte', sa.String(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fim', sa.DateTime(), nullable=True),
    sa.Column('registros', sa.Integer(), nullable=False),
    sa.Column('erro', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('papel', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=True),
    sa.Column('convite_token', sa.String(), nullable=True),
    sa.Column('convite_expira', sa.DateTime(), nullable=True),
    sa.Column('redefinir_token', sa.String(), nullable=True),
    sa.Column('redefinir_expira', sa.DateTime(), nullable=True),
    sa.Column('verticais', sa.JSON(), nullable=False),
    sa.Column('lider', sa.JSON(), nullable=False),
    sa.Column('pipedrive_user_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('convite_token'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('redefinir_token')
    )
    op.create_table('melhorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('prioridade', sa.String(), nullable=False),
    sa.Column('situacao', sa.String(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('melhorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_melhorias_situacao'), ['situacao'], unique=False)

    op.create_table('noticias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('fonte', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('publicada_em', sa.DateTime(), nullable=True),
    sa.Column('coletada_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'url')
    )
    with op.batch_alter_table('noticias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_noticias_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_noticias_publicada_em'), ['publicada_em'], unique=False)

    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('nome_normalizado', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('pipedrive_person_id', sa.Integer(), nullable=True),
    sa.Column('fonte', sa.String(), nullable=False),
    sa.Column('senioridade', sa.String(), nullable=True),
    sa.Column('score_relacionamento', sa.Float(), nullable=False),
    sa.Column('score_componentes', sa.JSON(), nullable=False),
    sa.Column('ponto_focal', sa.Boolean(), nullable=False),
    sa.Column('temperatura', sa.String(), nullable=True),
    sa.Column('temperatura_motivo', sa.String(), nullable=True),
    sa.Column('temperatura_em', sa.DateTime(), nullable=True),
    sa.Column('linkedin_headline', sa.String(), nullable=True),
    sa.Column('linkedin_empresa_atual', sa.String(), nullable=True),
    sa.Column('linkedin_em', sa.DateTime(), nullable=True),
    sa.Column('linkedin_pedido_em', sa.DateTime(), nullable=True),
    sa.Column('linkedin_busca_em', sa.DateTime(), nullable=True),
    sa.Column('linkedin_nao_encontrado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pessoas_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_pessoas_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_pessoas_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pessoas_nome_normalizado'), ['nome_normalizado'], unique=False)
        batch_op.create_index(batch_op.f('ix_pessoas_pipedrive_person_id'), ['pipedrive_person_id'], unique=False)

    op.create_table('sessoes',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('expira', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('sessoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessoes_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('interacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('usuario_email', sa.String(), nullable=False),
    sa.Column('email_externo', sa.String(), nullable=False),
    sa.Column('direcao', sa.String(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'email_externo')
    )
    with op.batch_alter_table('interacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interacoes_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_interacoes_email_externo'), ['email_externo'], unique=False)
        batch_op.create_index(batch_op.f('ix_interacoes_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interacoes_pessoa_id'), ['pessoa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interacoes_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interacoes_usuario_email'), ['usuario_email'], unique=False)

    op.create_table('negocios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.Column('vertical', sa.String(), nullable=True),
    sa.Column('fonte', sa.String(), nullable=False),
    sa.Column('id_externo', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('pipeline_id', sa.Integer(), nullable=True),
    sa.Column('etapa', sa.String(), nullable=True),
    sa.Column('pipedrive_owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('produto', sa.String(), nullable=True),
    sa.Column('seguradora', sa.String(), nullable=True),
    sa.Column('inicio_vigencia', sa.Date(), nullable=True),
    sa.Column('fim_vigencia', sa.Date(), nullable=True),
    sa.Column('ganho_em', sa.Date(), nullable=True),
    sa.Column('valor', sa.Double(), nullable=True),
    sa.Column('vidas', sa.Integer(), nullable=True),
    sa.Column('responsavel_email', sa.String(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fonte', 'id_externo')
    )
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negocios_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_negocios_pessoa_id'), ['pessoa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_negocios_pipeline_id'), ['pipeline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_negocios_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_negocios_vertical'), ['vertical'], unique=False)

    op.create_table('atividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipedrive_id', sa.Integer(), nullable=True),
    sa.Column('negocio_id', sa.Integer(), nullable=True),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('assunto', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('criada_por_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.String(), nullable=True),
    sa.Column('concluida', sa.Boolean(), nullable=False),
    sa.Column('concluida_em', sa.DateTime(), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criada_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipedrive_id')
    )
    with op.batch_alter_table('atividades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atividades_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_atividades_negocio_id'), ['negocio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_atividades_pessoa_id'), ['pessoa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_atividades_responsavel_id'), ['responsavel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_atividades_vencimento'), ['vencimento'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atividades_vencimento'))
        batch_op.drop_index(batch_op.f('ix_atividades_responsavel_id'))
        batch_op.drop_index(batch_op.f('ix_atividades_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_atividades_negocio_id'))
        batch_op.drop_index(batch_op.f('ix_atividades_empresa_id'))

    op.drop_table('atividades')
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negocios_vertical'))
        batch_op.drop_index(batch_op.f('ix_negocios_status'))
        batch_op.drop_index(batch_op.f('ix_negocios_pipeline_id'))
        batch_op.drop_index(batch_op.f('ix_negocios_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_negocios_empresa_id'))

    op.drop_table('negocios')
    with op.batch_alter_table('interacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interacoes_usuario_email'))
        batch_op.drop_index(batch_op.f('ix_interacoes_thread_id'))
        batch_op.drop_index(batch_op.f('ix_interacoes_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_interacoes_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_interacoes_email_externo'))
        batch_op.drop_index(batch_op.f('ix_interacoes_data'))

    op.drop_table('interacoes')
    with op.batch_alter_table('sessoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessoes_usuario_id'))

    op.drop_table('sessoes')
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pessoas_pipedrive_person_id'))
        batch_op.drop_index(batch_op.f('ix_pessoas_nome_normalizado'))
        batch_op.drop_index(batch_op.f('ix_pessoas_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_pessoas_email'))
        batch_op.drop_index(batch_op.f('ix_pessoas_cpf'))

    op.drop_table('pessoas')
    with op.batch_alter_table('noticias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_noticias_publicada_em'))
        batch_op.drop_index(batch_op.f('ix_noticias_empresa_id'))

    op.drop_table('noticias')
    with op.batch_alter_table('melhorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_melhorias_situacao'))

    op.drop_table('melhorias')
    op.drop_table('usuarios')
    op.drop_table('sync_log')
    op.drop_table('qualidade_ignoradas')
    with op.batch_alter_table('linkedin_pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_linkedin_pedidos_id_alvo'))
        batch_op.drop_index(batch_op.f('ix_linkedin_pedidos_criado_em'))
        batch_op.drop_index(batch_op.f('ix_linkedin_pedidos_concluido_em'))

    op.drop_table('linkedin_pedidos')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_pipedrive_org_id'))
        batch_op.drop_index(batch_op.f('ix_empresas_nome_normalizado'))
        batch_op.drop_index(batch_op.f('ix_empresas_dominio'))
        batch_op.drop_index(batch_op.f('ix_empresas_cnpj'))

    op.drop_table('empresas')
    # ### end Alembic commands ###
