"""configurações alteradas pelo master na plataforma (ex.: modelo da IA da temperatura)

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 16:10:34.458701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('chave', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('chave')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
