"""praca de saude, cidade manual e cnpj do site

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-07 21:14:01.927163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade_fonte', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cidade_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('praca', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('praca_fatia', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('praca_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('site_cnpj_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('site_cnpj_em')
        batch_op.drop_column('praca_em')
        batch_op.drop_column('praca_fatia')
        batch_op.drop_column('praca')
        batch_op.drop_column('cidade_em')
        batch_op.drop_column('cidade_fonte')

    # ### end Alembic commands ###
